spring.datasource.url=jdbc:mysql://localhost:3306/rick_and_morty_universe
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=oiY39Pnq#H71gJ&
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=validate
